### ISSUE TITLE
_handlePaymentError is not working in release mode in Flutter Web.

### ISSUE THREAD

**Issue by HalffTime** [priyaranjan12345/flutter_razorpay_web#2]
_handlePaymentError is working in debug mode, but is not working in release mode,  _handlePaymentSuccess seems to be fine.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.0)
[✓] Connected device (2 available)
[✓] Network resources

**Comment by priyaranjan12345** [comment]
@HalffTime I tested it thoroughly but it seems to be working fine in release mode. Please give a reproducible example.

**Comment by HalffTime** [comment]
@priyaranjan12345 Never mind I figured it out! It was an issue from my side. Thank you for your package!
